# Generated by Django 5.0.4 on 2024-04-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_compensacao', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
